### ISSUE TITLE
Create resources providers abstraction class (Windows/Linux)

### ISSUE THREAD

**Issue by poskart** [saleph/ZPR_ResMonitor#1]
Create abstraction class with resources providers abstract methods for CPU, RAM and disk usage depending on Windows or Linux using conditionally-included system-specific files.

**Comment by saleph** [comment]
Wouldn't be better to simply provide an abstract with 3 functions, each returning a class like `RAMState` and within `currentMBTaken, currentPercentageTaken`? These operations are like plain C coding, so another abstract layer may be an overhead (and later - the requirement to have only ONE place with `#ifdef PLATFORM` will be charmed).

**Comment by poskart** [comment]
It'd be better unless we assume not to implement resource-specific operations. This approach with 3 abstract for each resource is more generic, though one general abstraction class could be sufficient. It could be anyway for the start...we can implement one abstraction and correct it later in case of troubles..

**Comment by saleph** [comment]
What you mean by "resource-specific operations"? Simple "poll OS for value, pack and return" wouldn't meet project requirements?

**Comment by poskart** [comment]
It would, I only preferred more generic approach to have all resources separated. Anyway, lets try with single abstract class.

**Comment by saleph** [comment]
Great, poke when it will be ready. Remember about dev and derivative branches

**Comment by poskart** [comment]
Done
